#!/bin/bash
echo "Начать? y/n"
read str
while [ "$str" = y ] 
do
sudo passwd -aS
echo "введите имя пользователя из списка выше"
read a
echo "минимальное время жизни пароля(поле) и максимальное время жизни пароля(5 поле)"
sudo passwd -S $a


echo "установить минимальное время жизни пароля? y/n"
read yn
case "$yn" in
	y)
read min
sudo passwd -n $min $a
sudo passwd -S $a
;;
n)
	esac
echo "установить максимальное время жизни пароля? y/n"
read yn
case "$yn" in
	y)
read max
sudo passwd -x $max $a
sudo passwd -S $a
;;
n)
	esac
	echo "Изменить пароль согласно требованиям? y/n"
	read yn
	case "$yn" in
		y)
sudo passwd $a
;;
n)
	esac
	sudo passwd -S $a

	echo "Продолжить? y/n"


	read str
	if ["$str" = y]
	then 
	continue
fi	
done


